// 이상형 월드컵 테마 데이터
// image 경로는 나중에 실제 에셋으로 교체 예정 (현재 플레이스홀더)

const placeholder = (text) =>
  `https://placehold.co/400x300/EDE0F5/7B4FA6?text=${encodeURIComponent(text)}`;

export const THEMES = [
  {
    id: 'food',
    emoji: '🍔',
    name: '음식',
    description: '최고의 음식을 골라봐요!',
    color: '#FF6B35',
    items: [
      { id: 'pizza',      name: '피자',     emoji: '🍕', image: placeholder('피자') },
      { id: 'burger',     name: '햄버거',   emoji: '🍔', image: placeholder('햄버거') },
      { id: 'tteokbokki', name: '떡볶이',   emoji: '🌶️', image: placeholder('떡볶이') },
      { id: 'sushi',      name: '초밥',     emoji: '🍣', image: placeholder('초밥') },
      { id: 'ramen',      name: '라면',     emoji: '🍜', image: placeholder('라면') },
      { id: 'chicken',    name: '치킨',     emoji: '🍗', image: placeholder('치킨') },
      { id: 'samgyeopsal',name: '삼겹살',   emoji: '🥩', image: placeholder('삼겹살') },
      { id: 'jjajang',    name: '짜장면',   emoji: '🍝', image: placeholder('짜장면') },
      { id: 'galbi',      name: '갈비',     emoji: '🍖', image: placeholder('갈비') },
      { id: 'bibimbap',   name: '비빔밥',   emoji: '🥗', image: placeholder('비빔밥') },
      { id: 'cold_noodle',name: '냉면',     emoji: '🍱', image: placeholder('냉면') },
      { id: 'kimchi',     name: '김치찌개', emoji: '🫕', image: placeholder('김치찌개') },
      { id: 'doenjang',   name: '된장찌개', emoji: '🫕', image: placeholder('된장찌개') },
      { id: 'pasta',      name: '파스타',   emoji: '🍝', image: placeholder('파스타') },
      { id: 'steak',      name: '스테이크', emoji: '🥩', image: placeholder('스테이크') },
      { id: 'kimbap',     name: '김밥',     emoji: '🌯', image: placeholder('김밥') },
      { id: 'jjigae',     name: '순두부찌개',emoji: '🫕', image: placeholder('순두부찌개') },
      { id: 'bulgogi',    name: '불고기',   emoji: '🥩', image: placeholder('불고기') },
      { id: 'bossam',     name: '보쌈',     emoji: '🥬', image: placeholder('보쌈') },
      { id: 'jjimdak',    name: '찜닭',     emoji: '🍗', image: placeholder('찜닭') },
      { id: 'hotdog',     name: '핫도그',   emoji: '🌭', image: placeholder('핫도그') },
      { id: 'tacos',      name: '타코',     emoji: '🌮', image: placeholder('타코') },
      { id: 'curry',      name: '카레',     emoji: '🍛', image: placeholder('카레') },
      { id: 'fried_rice', name: '볶음밥',   emoji: '🍳', image: placeholder('볶음밥') },
      { id: 'jeon',       name: '전',       emoji: '🥞', image: placeholder('전') },
      { id: 'sundae',     name: '순대',     emoji: '🌭', image: placeholder('순대') },
      { id: 'mandu',      name: '만두',     emoji: '🥟', image: placeholder('만두') },
      { id: 'haemul',     name: '해물탕',   emoji: '🦞', image: placeholder('해물탕') },
      { id: 'budae',      name: '부대찌개', emoji: '🫕', image: placeholder('부대찌개') },
      { id: 'shabu',      name: '샤브샤브', emoji: '🍲', image: placeholder('샤브샤브') },
      { id: 'udon',       name: '우동',     emoji: '🍜', image: placeholder('우동') },
      { id: 'tonkotsu',   name: '돈코츠라멘',emoji: '🍜', image: placeholder('돈코츠라멘') },
    ],
  },
  {
    id: 'travel',
    emoji: '✈️',
    name: '여행지',
    description: '다음 여행지를 골라봐요!',
    color: '#3A86FF',
    items: [
      { id: 'jeju',       name: '제주도',   emoji: '🌺', image: placeholder('제주도') },
      { id: 'busan',      name: '부산',     emoji: '🌊', image: placeholder('부산') },
      { id: 'gyeongju',   name: '경주',     emoji: '🏯', image: placeholder('경주') },
      { id: 'tokyo',      name: '도쿄',     emoji: '🗼', image: placeholder('도쿄') },
      { id: 'osaka',      name: '오사카',   emoji: '🏯', image: placeholder('오사카') },
      { id: 'paris',      name: '파리',     emoji: '🗼', image: placeholder('파리') },
      { id: 'barcelona',  name: '바르셀로나',emoji: '🏖️', image: placeholder('바르셀로나') },
      { id: 'new_york',   name: '뉴욕',     emoji: '🗽', image: placeholder('뉴욕') },
      { id: 'london',     name: '런던',     emoji: '🎡', image: placeholder('런던') },
      { id: 'sydney',     name: '시드니',   emoji: '🦘', image: placeholder('시드니') },
      { id: 'bali',       name: '발리',     emoji: '🌴', image: placeholder('발리') },
      { id: 'hawaii',     name: '하와이',   emoji: '🌺', image: placeholder('하와이') },
      { id: 'maldives',   name: '몰디브',   emoji: '🏝️', image: placeholder('몰디브') },
      { id: 'phuket',     name: '푸켓',     emoji: '🌴', image: placeholder('푸켓') },
      { id: 'taipei',     name: '타이베이', emoji: '🧋', image: placeholder('타이베이') },
      { id: 'singapore',  name: '싱가포르', emoji: '🌆', image: placeholder('싱가포르') },
      { id: 'prague',     name: '프라하',   emoji: '🏰', image: placeholder('프라하') },
      { id: 'vienna',     name: '빈',       emoji: '🎭', image: placeholder('빈') },
      { id: 'rome',       name: '로마',     emoji: '🏛️', image: placeholder('로마') },
      { id: 'amsterdam',  name: '암스테르담',emoji: '🚲', image: placeholder('암스테르담') },
      { id: 'dubai',      name: '두바이',   emoji: '🏙️', image: placeholder('두바이') },
      { id: 'istanbul',   name: '이스탄불', emoji: '🕌', image: placeholder('이스탄불') },
      { id: 'cairo',      name: '카이로',   emoji: '🏺', image: placeholder('카이로') },
      { id: 'barcelona2', name: '그라나다', emoji: '🏰', image: placeholder('그라나다') },
      { id: 'lisbon',     name: '리스본',   emoji: '🛤️', image: placeholder('리스본') },
      { id: 'montreal',   name: '몬트리올', emoji: '🍁', image: placeholder('몬트리올') },
      { id: 'rio',        name: '리우데자네이루',emoji: '🎭', image: placeholder('리우') },
      { id: 'zanzibar',   name: '잔지바르', emoji: '🌊', image: placeholder('잔지바르') },
      { id: 'santorini',  name: '산토리니', emoji: '⛵', image: placeholder('산토리니') },
      { id: 'fjord',      name: '노르웨이 피요르드',emoji: '🏔️', image: placeholder('피요르드') },
      { id: 'machu',      name: '마추픽추', emoji: '🏔️', image: placeholder('마추픽추') },
      { id: 'hokkaido',   name: '홋카이도', emoji: '⛷️', image: placeholder('홋카이도') },
    ],
  },
  {
    id: 'activity',
    emoji: '🎪',
    name: '놀거리',
    description: '같이 하고 싶은 걸 골라봐요!',
    color: '#43A047',
    items: [
      { id: 'movie',      name: '영화관',   emoji: '🎬', image: placeholder('영화관') },
      { id: 'nanta',      name: '공연 관람', emoji: '🎭', image: placeholder('공연관람') },
      { id: 'picnic',     name: '피크닉',   emoji: '🧺', image: placeholder('피크닉') },
      { id: 'amusement',  name: '놀이공원', emoji: '🎡', image: placeholder('놀이공원') },
      { id: 'hiking',     name: '등산',     emoji: '🏔️', image: placeholder('등산') },
      { id: 'camping',    name: '캠핑',     emoji: '⛺', image: placeholder('캠핑') },
      { id: 'beach',      name: '해변 드라이브',emoji: '🚗', image: placeholder('드라이브') },
      { id: 'karaoke',    name: '노래방',   emoji: '🎤', image: placeholder('노래방') },
      { id: 'cooking',    name: '요리 클래스',emoji: '👨‍🍳', image: placeholder('요리클래스') },
      { id: 'escape',     name: '방탈출',   emoji: '🔐', image: placeholder('방탈출') },
      { id: 'arcade',     name: '오락실',   emoji: '🕹️', image: placeholder('오락실') },
      { id: 'bowling',    name: '볼링',     emoji: '🎳', image: placeholder('볼링') },
      { id: 'art',        name: '미술관',   emoji: '🖼️', image: placeholder('미술관') },
      { id: 'craft',      name: '공예 체험', emoji: '🎨', image: placeholder('공예체험') },
      { id: 'photo',      name: '사진 스튜디오',emoji: '📸', image: placeholder('사진스튜디오') },
      { id: 'board_game', name: '보드게임 카페',emoji: '🎲', image: placeholder('보드게임') },
      { id: 'night_market',name: '야시장',  emoji: '🏮', image: placeholder('야시장') },
      { id: 'jazz_bar',   name: '재즈바',   emoji: '🎷', image: placeholder('재즈바') },
      { id: 'rooftop',    name: '루프탑 카페',emoji: '☕', image: placeholder('루프탑카페') },
      { id: 'han_river',  name: '한강 치킨', emoji: '🍗', image: placeholder('한강치킨') },
      { id: 'stargazing', name: '별 보기',   emoji: '⭐', image: placeholder('별보기') },
      { id: 'flower',     name: '꽃 구경',   emoji: '🌸', image: placeholder('꽃구경') },
      { id: 'pottery',    name: '도예 체험', emoji: '🏺', image: placeholder('도예체험') },
      { id: 'spa',        name: '온천/스파', emoji: '♨️', image: placeholder('온천스파') },
      { id: 'bungee',     name: '번지점프', emoji: '😱', image: placeholder('번지점프') },
      { id: 'snorkeling', name: '스노클링', emoji: '🤿', image: placeholder('스노클링') },
      { id: 'horse',      name: '승마',     emoji: '🐎', image: placeholder('승마') },
      { id: 'badminton',  name: '배드민턴', emoji: '🏸', image: placeholder('배드민턴') },
      { id: 'mini_golf',  name: '미니 골프', emoji: '⛳', image: placeholder('미니골프') },
      { id: 'haunted',    name: '공포 체험', emoji: '👻', image: placeholder('공포체험') },
      { id: 'reading',    name: '독립서점 투어',emoji: '📚', image: placeholder('서점투어') },
      { id: 'drive_in',   name: '드라이브인 영화',emoji: '🚘', image: placeholder('드라이브인') },
    ],
  },
  {
    id: 'sport',
    emoji: '💪',
    name: '운동',
    description: '같이 하고 싶은 운동을 골라봐요!',
    color: '#E53935',
    items: [
      { id: 'soccer',     name: '축구',     emoji: '⚽', image: placeholder('축구') },
      { id: 'basketball', name: '농구',     emoji: '🏀', image: placeholder('농구') },
      { id: 'tennis',     name: '테니스',   emoji: '🎾', image: placeholder('테니스') },
      { id: 'swimming',   name: '수영',     emoji: '🏊', image: placeholder('수영') },
      { id: 'yoga',       name: '요가',     emoji: '🧘', image: placeholder('요가') },
      { id: 'cycling',    name: '자전거',   emoji: '🚴', image: placeholder('자전거') },
      { id: 'running',    name: '러닝',     emoji: '🏃', image: placeholder('러닝') },
      { id: 'pilates',    name: '필라테스', emoji: '🤸', image: placeholder('필라테스') },
      { id: 'golf',       name: '골프',     emoji: '⛳', image: placeholder('골프') },
      { id: 'climbing',   name: '클라이밍', emoji: '🧗', image: placeholder('클라이밍') },
      { id: 'skiing',     name: '스키',     emoji: '⛷️', image: placeholder('스키') },
      { id: 'surfing',    name: '서핑',     emoji: '🏄', image: placeholder('서핑') },
      { id: 'boxing',     name: '복싱',     emoji: '🥊', image: placeholder('복싱') },
      { id: 'martial',    name: '태권도',   emoji: '🥋', image: placeholder('태권도') },
      { id: 'baseball',   name: '야구',     emoji: '⚾', image: placeholder('야구') },
      { id: 'volleyball', name: '배구',     emoji: '🏐', image: placeholder('배구') },
      { id: 'table_tennis',name: '탁구',   emoji: '🏓', image: placeholder('탁구') },
      { id: 'archery',    name: '양궁',     emoji: '🏹', image: placeholder('양궁') },
      { id: 'skating',    name: '스케이트', emoji: '⛸️', image: placeholder('스케이트') },
      { id: 'crossfit',   name: '크로스핏', emoji: '🏋️', image: placeholder('크로스핏') },
      { id: 'hiking2',    name: '트레킹',   emoji: '🥾', image: placeholder('트레킹') },
      { id: 'dance',      name: '댄스',     emoji: '💃', image: placeholder('댄스') },
      { id: 'horse2',     name: '승마',     emoji: '🐎', image: placeholder('승마') },
      { id: 'rowing',     name: '카약',     emoji: '🚣', image: placeholder('카약') },
      { id: 'squash',     name: '스쿼시',   emoji: '🎾', image: placeholder('스쿼시') },
      { id: 'trampoline', name: '트램폴린', emoji: '🤸', image: placeholder('트램폴린') },
      { id: 'darts',      name: '다트',     emoji: '🎯', image: placeholder('다트') },
      { id: 'billiard',   name: '당구',     emoji: '🎱', image: placeholder('당구') },
      { id: 'frisbee',    name: '프리스비', emoji: '🥏', image: placeholder('프리스비') },
      { id: 'rugby',      name: '럭비',     emoji: '🏉', image: placeholder('럭비') },
      { id: 'fencing',    name: '펜싱',     emoji: '🤺', image: placeholder('펜싱') },
      { id: 'badminton2', name: '배드민턴', emoji: '🏸', image: placeholder('배드민턴') },
    ],
  },
  {
    id: 'drama',
    emoji: '🎬',
    name: '영화/드라마',
    description: '같이 보고 싶은 장르를 골라봐요!',
    color: '#7B4FA6',
    items: [
      { id: 'romance',    name: '로맨스',       emoji: '💕', image: placeholder('로맨스') },
      { id: 'action',     name: '액션',         emoji: '💥', image: placeholder('액션') },
      { id: 'horror',     name: '공포',         emoji: '👻', image: placeholder('공포') },
      { id: 'comedy',     name: '코미디',       emoji: '😂', image: placeholder('코미디') },
      { id: 'thriller',   name: '스릴러',       emoji: '😰', image: placeholder('스릴러') },
      { id: 'sf',         name: 'SF',           emoji: '🚀', image: placeholder('SF') },
      { id: 'fantasy',    name: '판타지',       emoji: '🧙', image: placeholder('판타지') },
      { id: 'animation',  name: '애니메이션',   emoji: '🎠', image: placeholder('애니메이션') },
      { id: 'documentary',name: '다큐멘터리',   emoji: '📹', image: placeholder('다큐멘터리') },
      { id: 'historical', name: '사극',         emoji: '👑', image: placeholder('사극') },
      { id: 'crime',      name: '범죄',         emoji: '🔍', image: placeholder('범죄') },
      { id: 'mystery',    name: '미스터리',     emoji: '🕵️', image: placeholder('미스터리') },
      { id: 'musical',    name: '뮤지컬',       emoji: '🎵', image: placeholder('뮤지컬') },
      { id: 'melodrama',  name: '멜로드라마',   emoji: '😭', image: placeholder('멜로드라마') },
      { id: 'sports_drama',name: '스포츠물',    emoji: '🏆', image: placeholder('스포츠물') },
      { id: 'noir',       name: '느와르',       emoji: '🌃', image: placeholder('느와르') },
      { id: 'romcom',     name: '로맨틱 코미디',emoji: '💑', image: placeholder('로맨틱코미디') },
      { id: 'disaster',   name: '재난',         emoji: '🌪️', image: placeholder('재난') },
      { id: 'war',        name: '전쟁',         emoji: '⚔️', image: placeholder('전쟁') },
      { id: 'superhero',  name: '슈퍼히어로',   emoji: '🦸', image: placeholder('슈퍼히어로') },
      { id: 'kdrama_romance',name: 'K-로맨스 드라마',emoji: '📺', image: placeholder('K로맨스드라마') },
      { id: 'usa_drama',  name: '미드',         emoji: '🎭', image: placeholder('미드') },
      { id: 'anime',      name: '일본 애니',    emoji: '🌸', image: placeholder('일본애니') },
      { id: 'netflix',    name: '넷플릭스 오리지널',emoji: '🔴', image: placeholder('넷플릭스') },
      { id: 'family',     name: '가족 영화',    emoji: '👨‍👩‍👧', image: placeholder('가족영화') },
      { id: 'bio',        name: '전기/실화',    emoji: '📖', image: placeholder('전기실화') },
      { id: 'zombie',     name: '좀비물',       emoji: '🧟', image: placeholder('좀비물') },
      { id: 'spy',        name: '첩보',         emoji: '🕵️', image: placeholder('첩보') },
      { id: 'court',      name: '법정 드라마',  emoji: '⚖️', image: placeholder('법정드라마') },
      { id: 'medical',    name: '의학 드라마',  emoji: '🏥', image: placeholder('의학드라마') },
      { id: 'school',     name: '학교 드라마',  emoji: '🏫', image: placeholder('학교드라마') },
      { id: 'fantasy_romance',name: '판타지 로맨스',emoji: '🧚', image: placeholder('판타지로맨스') },
    ],
  },
  {
    id: 'cafe',
    emoji: '☕',
    name: '카페 음료',
    description: '최애 카페 음료를 골라봐요!',
    color: '#795548',
    items: [
      { id: 'americano',  name: '아메리카노',   emoji: '☕', image: placeholder('아메리카노') },
      { id: 'latte',      name: '라떼',         emoji: '🥛', image: placeholder('라떼') },
      { id: 'cappuccino', name: '카푸치노',     emoji: '☕', image: placeholder('카푸치노') },
      { id: 'cold_brew',  name: '콜드브루',     emoji: '🧊', image: placeholder('콜드브루') },
      { id: 'matcha',     name: '말차 라떼',    emoji: '🍵', image: placeholder('말차라떼') },
      { id: 'vanilla',    name: '바닐라 라떼',  emoji: '🌿', image: placeholder('바닐라라떼') },
      { id: 'caramel',    name: '카라멜 마키아또',emoji: '🍮', image: placeholder('카라멜마키아또') },
      { id: 'boba',       name: '버블티',       emoji: '🧋', image: placeholder('버블티') },
      { id: 'strawberry', name: '딸기 스무디',  emoji: '🍓', image: placeholder('딸기스무디') },
      { id: 'mango',      name: '망고 스무디',  emoji: '🥭', image: placeholder('망고스무디') },
      { id: 'lemonade',   name: '레모네이드',   emoji: '🍋', image: placeholder('레모네이드') },
      { id: 'ade',        name: '에이드',       emoji: '🍹', image: placeholder('에이드') },
      { id: 'hot_choco',  name: '핫초코',       emoji: '🍫', image: placeholder('핫초코') },
      { id: 'chamomile',  name: '캐모마일',     emoji: '🌼', image: placeholder('캐모마일') },
      { id: 'earl_grey',  name: '얼그레이',     emoji: '🫖', image: placeholder('얼그레이') },
      { id: 'milk_tea',   name: '밀크티',       emoji: '🍵', image: placeholder('밀크티') },
      { id: 'espresso',   name: '에스프레소',   emoji: '☕', image: placeholder('에스프레소') },
      { id: 'frappe',     name: '프라페',       emoji: '🥤', image: placeholder('프라페') },
      { id: 'tiramisu',   name: '티라미수 라떼',emoji: '🍰', image: placeholder('티라미수라떼') },
      { id: 'taro',       name: '타로 라떼',    emoji: '💜', image: placeholder('타로라떼') },
      { id: 'lavender',   name: '라벤더 라떼',  emoji: '💐', image: placeholder('라벤더라떼') },
      { id: 'coconut',    name: '코코넛 라떼',  emoji: '🥥', image: placeholder('코코넛라떼') },
      { id: 'orange',     name: '오렌지 주스',  emoji: '🍊', image: placeholder('오렌지주스') },
      { id: 'peach_tea',  name: '복숭아 아이스티',emoji: '🍑', image: placeholder('복숭아아이스티') },
      { id: 'yogurt',     name: '요거트 스무디',emoji: '🫙', image: placeholder('요거트스무디') },
      { id: 'rose_latte', name: '로즈 라떼',    emoji: '🌹', image: placeholder('로즈라떼') },
      { id: 'cinnamon',   name: '시나몬 라떼',  emoji: '🫙', image: placeholder('시나몬라떼') },
      { id: 'walnut',     name: '호두 라떼',    emoji: '🌰', image: placeholder('호두라떼') },
      { id: 'pumpkin',    name: '단호박 라떼',  emoji: '🎃', image: placeholder('단호박라떼') },
      { id: 'ginger',     name: '진저 라떼',    emoji: '🫚', image: placeholder('진저라떼') },
      { id: 'oreo',       name: '오레오 스무디',emoji: '🍪', image: placeholder('오레오스무디') },
      { id: 'nutella',    name: '누텔라 라떼',  emoji: '🍫', image: placeholder('누텔라라떼') },
    ],
  },
];

// 유효한 대진 크기 계산: 데이터 수 이하의 최대 2의 제곱수
export function calcBracketSize(itemCount, requested) {
  const sizes = [128, 64, 32, 16, 8];
  const valid = sizes.filter(s => s <= itemCount);
  if (valid.length === 0) return 4;
  if (requested && valid.includes(requested)) return requested;
  return valid[0];
}

// Fisher-Yates 셔플
export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// 라운드 이름
export function getRoundName(remaining) {
  if (remaining === 2)  return '결승';
  if (remaining <= 4)   return '4강';
  if (remaining <= 8)   return '8강';
  if (remaining <= 16)  return '16강';
  if (remaining <= 32)  return '32강';
  if (remaining <= 64)  return '64강';
  return '128강';
}
